[package]
name = "simple_rocket"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.sqlx]
version = "0.8.2"
features = ["runtime-tokio","postgres","derive","macros","migrate","uuid","chrono"] 

[dependencies.rocket]
version = "0.5.1"
